version: '3.8'

services:
  object-detection:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5173:5173"  # Replace with desired port
    volumes:
      - ./video:/video  # Mount folder for video files if needed
    command: python3 app.py
